# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

norm_laplacian <- function(Adj, norm = 1L) {
    .Call('_infoCoRe_norm_laplacian', PACKAGE = 'infoCoRe', Adj, norm)
}

norm_laplacian_cx <- function(Adj, weighted = 0L, norm = 1L) {
    .Call('_infoCoRe_norm_laplacian_cx', PACKAGE = 'infoCoRe', Adj, weighted, norm)
}

driver <- function(Adj, weighted = 0L, directed = 0L, norm = 1L) {
    invisible(.Call('_infoCoRe_driver', PACKAGE = 'infoCoRe', Adj, weighted, directed, norm))
}

