# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_eig <- function(x, eigval, eigvec) {
    invisible(.Call('_infoCoRe_get_eig', PACKAGE = 'infoCoRe', x, eigval, eigvec))
}

get_eig_cx <- function(x, eigval, eigvec) {
    invisible(.Call('_infoCoRe_get_eig_cx', PACKAGE = 'infoCoRe', x, eigval, eigvec))
}

laplacian <- function(Adj, norm = 1L) {
    .Call('_infoCoRe_laplacian', PACKAGE = 'infoCoRe', Adj, norm)
}

laplacian_cx <- function(Adj, weighted = 0L, norm = 1L) {
    .Call('_infoCoRe_laplacian_cx', PACKAGE = 'infoCoRe', Adj, weighted, norm)
}

driver <- function(Adj, weighted = 0L, directed = 0L, norm = 1L) {
    invisible(.Call('_infoCoRe_driver', PACKAGE = 'infoCoRe', Adj, weighted, directed, norm))
}

